### ISSUE TITLE
各部分的统一入口

### ISSUE THREAD

**Issue by Lafite-Yu** [sebuaa2019/Team104#4]
通过一个统一入口调用所有功能，开始执行整个项目而不是通过bash分别运行每一部分

**Comment by JavieraStephanie** [comment]
已在GUI的代码里添加这功能 （https://github.com/sebuaa2019/Team104/commit/59c536fddd14807a739dd70229df17b9e18a6233），所以只需要catkin_make; rosrun rosvis rosvis;之后系统也会同意执行其他roslaunch指令

**Comment by Lafite-Yu** [comment]
使用GUI的统一入口无法在命令行得到运行状态的提示，撤销更改暂时搁置

**Comment by JavieraStephanie** [comment]
Fixed in commit https://github.com/sebuaa2019/Team104/commit/06c608fa5646bf182bd7c73c0e344ba81a6b1b26
