### ISSUE TITLE
物品识别无法识别到从摄像头获取到的图像中的水瓶等

### ISSUE THREAD

**Issue by Lafite-Yu** [sebuaa2019/Team104#6]
可能的原因：
1. 摄像头的高度等参数不好，导致获取到的图像角度有问题
2. 获取到的图片中水平所占面积过小
2. 物品识别API对于小物体的识别不好

**Comment by JavieraStephanie** [comment]
关于物品获取，即便使用原来的程序物品高度也不对，但是上周四展示时助教已把物品获取的相关代码调好已经可以获取物品正确的位置及高度，所以有可能这问题已解决

**Comment by Lafite-Yu** [comment]
对于无法正确识别出图片中的目标物体：
1. 使用Data augment的方法，当整幅图片无法识别出需要的物品时，对图片进行切分，提高可能存在的目标物的占比以提高识别准确率
2. 当多次尝试也无法识别出时，将航点记录为‘Unknown’，以不影响后续程序运行

对于无法正确抓取到物体的位置：
考虑是由于上次机器人机械臂损坏重新安装后，kinect没有校准好，参见上一条
