### ISSUE TITLE
GUI进行运动控制经常出现卡死

### ISSUE THREAD

**Issue by Lafite-Yu** [sebuaa2019/Team104#7]
GUI本身出现卡死，窗口未响应，或GUI没有卡死但运动无反应，重启机器人后恢复

**Comment by JavieraStephanie** [comment]
考虑到的解决方案：
1. 关掉rviz的自动执行（rviz占用挺大的内存）
2. 提高各个功能的效率，尽量减少内存的使用

**Comment by yiliu666** [comment]
gui和主程序放到一起了，不用再分开跑了

**Comment by JavieraStephanie** [comment]
已经把rviz关掉了
